# Generated by Django 4.2.1 on 2023-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=10)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
